In [10]:
import numpy 

# create an array with 27 elements
n = numpy.arange(21)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [14]:
# create a 3 dimensional array
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [16]:
m = numpy.asarray([[123, 12, 14, 123,12,33],[],[]])
m

array([[123, 12, 14, 123, 12, 33], [], []], dtype=object)

In [17]:
type(m)

numpy.ndarray

In [1]:
import os
os.sys.path
import cv2


ModuleNotFoundError: No module named 'cv2'

In [3]:
import cv2
im_g=cv2.imread("smallgray.png", 0) #0-grayscale, 1=brg
im_g

ModuleNotFoundError: No module named 'cv2'