In [1]:
2 ** 1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [2]:
import numpy as np

In [3]:
np.int64(2) ** 1000


0

## numpy array 

In [6]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
len(arr)

3

In [8]:
arr[2]

3

In [10]:
type(arr[1])

numpy.int64

In [11]:
arr.dtype

dtype('int64')

In [16]:
arr32 = np.array([1,2,3], dtype=np.int32)
arr32

array([1, 2, 3], dtype=int32)

In [19]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [20]:
%%time
v1 * v2

CPU times: user 4.14 ms, sys: 4.54 ms, total: 8.68 ms
Wall time: 6.92 ms


array([ 0.12029697,  0.15175927,  0.41422417, ...,  0.21412101,
        0.1820159 ,  0.05640711])

In [21]:
np.dot(arr, arr)

14

In [22]:
arr @ arr

14

In [25]:
mat = np.array([[1,2,3],[9,8,7],[4,5,6]])
mat

array([[1, 2, 3],
       [9, 8, 7],
       [4, 5, 6]])

In [26]:
v = np.arange(12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
v.reshape([4,3])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
mat = np.arange(12).reshape([4,3])
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
mat2 = mat.reshape([3, 4])
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
mat[2,1] = 92
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6, 92, 92],
       [ 9, 10, 11]])

In [40]:
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4, 92, 10],
       [ 2,  5, 92, 11]])

In [43]:
nums = np.arange(1,8)
nums [3:5]

array([4, 5])

In [47]:
mat[1,1] #first row, first column

4