In [1]:
2 ** 1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [2]:
import numpy as np

In [3]:
np.int64(2) ** 1000


0

## numpy array 

In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
len(arr)

3

In [6]:
arr[2]

3

In [7]:
type(arr[1])

numpy.int64

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr32 = np.array([1,2,3], dtype=np.int32)
arr32

array([1, 2, 3], dtype=int32)

In [10]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [11]:
%%time
v1 * v2

CPU times: user 4.74 ms, sys: 6.45 ms, total: 11.2 ms
Wall time: 14.6 ms


array([  3.89318591e-04,   4.91877608e-01,   8.35512820e-02, ...,
         4.40478455e-01,   1.86723258e-01,   2.12727248e-01])

In [12]:
np.dot(arr, arr)

14

In [13]:
arr @ arr

14

In [14]:
mat = np.array([[1,2,3],[9,8,7],[4,5,6]])
mat

array([[1, 2, 3],
       [9, 8, 7],
       [4, 5, 6]])

In [15]:
v = np.arange(12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
v.reshape([4,3])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
mat = np.arange(12).reshape([4,3])
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
mat2 = mat.reshape([3, 4])
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
mat[2,1] = 92
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6, 92,  8],
       [ 9, 10, 11]])

In [20]:
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4, 92, 10],
       [ 2,  5,  8, 11]])

In [21]:
nums = np.arange(1,8)
nums [3:5]

array([4, 5])

In [22]:
mat[1,1] #first row, first column

4

In [23]:
v = np.arange(12).reshape((3,4))
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
v[1,2] #2nd row, 2nd column

6

In [27]:
v[:, 1] #2nd element for every row

array([1, 5, 9])

In [29]:
v[1:, 2:] = 43 #set elements in an array
v

array([[ 0,  1,  2,  3],
       [ 4,  5, 43, 43],
       [ 8,  9, 43, 43]])

## Boolean Indexing

In [36]:
p = np.arange(3)
p

array([0, 1, 2])

In [37]:
p[np.array([True, False, True])] 

array([0, 2])

In [38]:
p > 1

array([False, False,  True], dtype=bool)

In [45]:
p[p>=1] #elements greater or equal to 1

array([1, 2])

In [46]:
q = np.arange(10)

In [47]:
q[(q>2)&(q<8)] #element greater than 2 AND less than 8

array([3, 4, 5, 6, 7])

In [48]:
q[(q>7)|(q<2)] #elements greater than 7 OR smaller than 2

array([0, 1, 8, 9])

In [51]:
q[~(q>7)] # Negate (NOTE use ~ instead of -)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [53]:
mat = np.random.rand(5, 6)
mat

array([[ 0.16006121,  0.73066454,  0.15429086,  0.50445257,  0.80502392,
         0.95021546],
       [ 0.42070301,  0.60387329,  0.67935988,  0.71761881,  0.3501356 ,
         0.28190321],
       [ 0.20184272,  0.12475056,  0.13977368,  0.42892784,  0.39392822,
         0.15894019],
       [ 0.90054983,  0.6186261 ,  0.21800543,  0.93655372,  0.65525435,
         0.90676739],
       [ 0.69931185,  0.01647941,  0.00252747,  0.82971802,  0.40116361,
         0.5820138 ]])

In [57]:
mat[np.abs(mat - mat.mean()) > 1.5*mat.std()]

array([ 0.95021546,  0.93655372,  0.01647941,  0.00252747])

In [60]:
np.abs(mat - mat.mean()) 
#Difference from mean for each value in the matrix.

array([[ 0.32572001,  0.24488332,  0.33149036,  0.01867136,  0.3192427 ,
         0.46443424],
       [ 0.06507821,  0.11809207,  0.19357866,  0.23183759,  0.13564562,
         0.20387801],
       [ 0.2839385 ,  0.36103066,  0.34600754,  0.05685338,  0.09185299,
         0.32684103],
       [ 0.41476861,  0.13284488,  0.26777579,  0.4507725 ,  0.16947313,
         0.42098617],
       [ 0.21353063,  0.46930181,  0.48325375,  0.34393681,  0.08461761,
         0.09623258]])

In [61]:
np.abs(mat - mat.mean()) > 1.5*mat.std()

array([[False, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [False,  True,  True, False, False, False]], dtype=bool)